### ISSUE TITLE
SNP filters in GEMMA

### ISSUE THREAD

**Issue by xiangzhu** [xiangzhou/GEMMA#19]
Hi Xiang,

is this "not" a typo? (page 14 in the manual)
> By default, SNPs with minor allele frequency above 1% will not be included in the analysis. 

if I plan to include all SNPs in the analysis, I just need to use "-maf 0"?

Another two related question:

- is `-notsnp` the same as `-miss 0 -maf 0 -r2 1 -hwe 0`?
- if I specify a list of SNPs to be included in the analysis by using the option `-snps`, will some of the SNPs still be filtered out due to the missingness and/or minor allele frequencies?

Thanks!

**Comment by xiangzhou** [comment]
Yes, that's a typo. You can just use "-maf 0" to include all SNPs (or more precisely, use "-miss 0 -maf 0 -r2 1 -hwe 0"). (1) "-notsnp" is not exactly the same as "-miss 0 -maf 0 -r2 1 -hwe 0" as it still check missingness and r2. (2) Even if you specify a list, some of them still could be filtered out.

**Comment by xiangzhu** [comment]
Thanks!

**Comment by wzuhou** [comment]
Hi Xiang,
I am running Gemma 0.98.1 with these options:
**-miss 0 -maf 0 -r2 1 -hwe 0 -snps my_snplist**
In principle, _all the variance_ in my input file should be analyzed, but I got the report looks like this:
```
## number of total SNPs/var        =    20829
## number of considered SNPS       =    20776
## number of analyzed SNPs         =     7695
```
So I think there is still filtering performed on the dataset. My questions are,
1) Could you specify what is the reason it does not analyze all the SNP with the above options? Is there any other default SNP filtering ? 
2) And what has been filtered out during the total>considered>analyzed steps?

And one little suggestion, is it possible to specify due to which QC step the variance were filtered out in log file? e.g. 1000 SNPs were filtered out due to missing genotype, etc.

**Comment by AndreAllegrini** [comment]
Hi,

was this solved? 

I also have the same issue.  Specifying flags for filtering such as   
-miss 0 \
 -maf 0 \
 -r2 1 \
 -hwe 0 \ 

I still miss ~half of the SNPS (from ~40million to ~20 million)

So it looks like there is some other sort of filtering performed? 
I'm using Gemma_0.98.1

thanks in advance

**Comment by pjotrp** [comment]
Please use the mailing list.

**Comment by alycemac** [comment]
Problem solved by using -miss 1

GEMMA manual typo

'SNPs with missingness below 5% will not be included in the analysis' should be 'SNPs with missingness above 5% will not be included in the analysis'

**Comment by 297B1** [comment]
hello！After I used '-miss 0 -maf 0 -r2 1 -hwe 0', there are still many missing snps.
Is there any other default SNP filtering ? What methods can I use to analyze all the SNPs? 
Thanks！
