### ISSUE TITLE
Makefile.macosx and gsl directory

### ISSUE THREAD

**Issue by fboehm** [xiangzhou/GEMMA#43]
I really appreciate the recent work that you've put into GEMMA. 

I received errors when trying to compile version 0.96 with the Makefile.macosx file. It seems that my gsl is in a directory other than the one listed in Makefile.macosx. I realize that there's a note about needing to change the directories listed in the Makefile, but I was unsure which lines typically need to be changed. The comment in Makefile.macosx about using caution when changing code below a certain line made me question whether I was proceeding as I should.

I installed gsl with homebrew, i.e., 

`brew install gsl`

I then changed all instances of gsl@1 to gsl in Makefile.macosx. Interestingly, I have on my computer both gsl and gsl@2 subdirectories, but no gsl@1 subdirectory. 

I believe that GEMMA now compiles and works as expected. 

My question is: why did you use the directory paths with gsl@1? Is it worth noting the possible need to make such a change in the documentation? It may not be needed, as, perhaps, most users are keener on this than am I. Thanks again.

**Comment by pcarbo** [comment]
@fboehm Thanks for the note. Yes, currently `Makefile.macosx` is not intended to work out-of-the-box, and will most likely need to be customized for a user's individual setup. I've included this Makefile as guidance only. We are working on improving the installation instructions and Makefile(s) so that the installation is more straightforward.

The specific problem you mentioned (regarding GSL and Homebrew) may have to do with the version of Homebrew I was using at the time on my MacBook Pro.

Certainly if you run into additional problems using GEMMA on Mac OS X, let us know.

**Comment by fboehm** [comment]
thanks for the explanation. It occurred to me after writing that the version of gsl might be the issue. thanks again!
